Features of Pandas:
*   High Performance data analysis tool.
*   Working with large data set.
*   Supports or load files with different formats.
*   More flexible to use.
*   Represents in Tabular way(rows and columns).
*   Working on missing data.
*   Indexing - Slicing - Subsetting the large data sets.
*   Merge and join two different datasets easily.
*   Reshape data sets.

In [ ]:
import pandas as pd

# Series

One Dimensional

Syntax: Series(data, index)

In [ ]:
l = [10,20,30,40]

In [ ]:
pd.Series(l)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
pd.Series(l, index=['i','ii','iii','iv'])

i      10
ii     20
iii    30
iv     40
dtype: int64

# Data Frame

Two Dimensional

Syntax: DataFrame(data)

In [ ]:
d = {'name':['sun','moon','star'], 'size':[100, 10, 1]}

In [ ]:
pd.DataFrame(d)

   name  size
0   sun   100
1  moon    10
2  star     1

# Panel

Multi Dimensional

Syntax: Panel(data, major axis, minor axis, dtype)